version: '3'

services:
  chemicalwebservice_rdkit:
    networks:
      - default
      - nginx-net
    command: /app/run_server.sh
    volumes:
      - ./logs:/app/logs:rw
    environment:
      VIRTUAL_HOST: structure.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: structure.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com

networks:
  nginx-net:
    external:
      name: nginx-net