version: '3'

services:
  redu-ms2-web:
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: gnps-structure.ucsd.edu
      VIRTUAL_PORT: 5066
      LETSENCRYPT_HOST: gnps-structure.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu

networks:
  nginx-net:
    external:
      name: nginx-net